import { escapeText } from './module-utils.js';
import { filterLabel, filterGroupLabel } from './presentation.js';

const frame=(title,body)=>`<section class="mui-b-dialog" role="dialog" aria-modal="true" aria-label="${escapeText(title)}" tabindex="-1"><header><strong>${escapeText(title)}</strong><button type="button" data-entry-close aria-label="關閉"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 6L18 18M18 6L6 18"/></svg></button></header><div class="mui-b-dialog-body">${body}</div></section>`;
const close='<button type="button" data-entry-close>取消</button>';
const actions=apply=>`<div class="mui-b-dialog-actions">${close}<button type="submit">${escapeText(apply)}</button></div><p data-entry-error role="status"></p>`;
const bindClose=ctx=>ctx.listen(ctx.root,'click',event=>{if(event.target.closest?.('[data-entry-close]'))ctx.services.dialogs?.close();});
const errorOf=e=>e?.message||String(e||'操作失敗');
const captureTarget=(ctx,kind,options={})=>{try{return{token:ctx.services.uiEntry.captureTarget(kind,options),error:null};}catch(error){return{token:null,error};}};
const boundToken=(state,override=null)=>{if(override)return override;if(state?.error)throw state.error;if(!state?.token)throw new Error('Target unavailable');return state.token;};
const lifetime=ctx=>{let alive=true;ctx.cleanup?.(()=>{alive=false;});return()=>alive;};

export function createEntryExternalImportDialogModule(){return{id:'ui-entry-003.dialog.external-import.v1',slot:'dialogs.content',mount(ctx){
  ctx.root.innerHTML=frame('開啟／匯入外部影像',`<form data-entry-form><label>檔案<input name="file" type="file" accept=".psd,.psb,.tif,.tiff,.exr,.raw,application/octet-stream" required></label>${actions('匯入')}</form>`);
  const form=ctx.root.querySelector('form');ctx.listen(form,'submit',async event=>{event.preventDefault();const file=form.elements.file.files?.[0],out=ctx.root.querySelector('[data-entry-error]');try{const result=await ctx.services.uiEntry.importExternal(file);if(result?.changed!==false)ctx.services.dialogs.close();else out.textContent='未匯入檔案';}catch(e){out.textContent=errorOf(e);}});bindClose(ctx);
}};}
export function createEntryIccDialogModule(){return{id:'ui-entry-003.dialog.icc.v1',slot:'dialogs.content',mount(ctx){
  ctx.root.innerHTML=frame('色彩描述檔',`<form><label>ICC / ICM<input name="file" type="file" accept=".icc,.icm" required></label>${actions('指派')}</form>`);const bound=captureTarget(ctx,'icc'),alive=lifetime(ctx),form=ctx.root.querySelector('form');ctx.listen(form,'submit',async event=>{event.preventDefault();const out=ctx.root.querySelector('[data-entry-error]');try{await ctx.services.uiEntry.assignIcc(form.elements.file.files?.[0],boundToken(bound),alive);if(alive())ctx.services.dialogs.close();}catch(e){out.textContent=errorOf(e);}});bindClose(ctx);
}};}
export function createEntrySelectMaskDialogModule({createOnly=false}={}){return{id:createOnly?'ui-entry-003.dialog.raster-mask.v1':'ui-entry-003.dialog.select-mask.v1',slot:'dialogs.content',mount(ctx){
  const bound=captureTarget(ctx,createOnly?'raster-mask':'select-mask');
  if(createOnly){ctx.root.innerHTML=frame('建立 Raster 遮色片',`<form><p>使用目前 Raster selection 建立所選影像的 rasterMask。</p>${actions('建立')}</form>`);const form=ctx.root.querySelector('form');ctx.listen(form,'submit',event=>{event.preventDefault();const out=ctx.root.querySelector('[data-entry-error]');try{ctx.services.uiEntry.createRasterMask(boundToken(bound));ctx.services.dialogs.close();}catch(e){out.textContent=errorOf(e);}});bindClose(ctx);return;}
  ctx.root.innerHTML=frame('選取並遮住',`<form><label>平滑<input name="smooth" type="number" min="0" max="20" value="0"></label><label>羽化<input name="feather" type="number" min="0" max="50" value="0"></label><label>擴張<input name="expand" type="number" min="-50" max="50" value="0"></label>${actions('套用')}</form>`);const form=ctx.root.querySelector('form');ctx.listen(form,'submit',event=>{event.preventDefault();const out=ctx.root.querySelector('[data-entry-error]');try{ctx.services.uiEntry.refineMask(Object.fromEntries(new FormData(form).entries()),boundToken(bound));ctx.services.dialogs.close();}catch(e){out.textContent=errorOf(e);}});bindClose(ctx);
}};}
export function createEntryLiquifyDialogModule(){return{id:'ui-entry-003.dialog.liquify.v1',slot:'dialogs.content',mount(ctx){
  const bound=captureTarget(ctx,'liquify');ctx.root.innerHTML=frame('液化',`<form><label>操作<select name="type"><option value="forwardWarp">向前扭曲</option><option value="twirl">旋轉</option><option value="pucker">內縮</option><option value="bloat">膨脹</option><option value="reconstruct">重建</option></select></label><label>半徑<input name="radius" type="number" min="1" value="80"></label><label>強度<input name="strength" type="number" min="-1" max="1" step=".05" value=".4"></label><label>水平位移<input name="dx" type="number" value="12"></label><label>垂直位移<input name="dy" type="number" value="0"></label><label><input name="freezeSelection" type="checkbox">保護目前 Raster selection</label>${actions('加入液化濾鏡')}</form>`);const form=ctx.root.querySelector('form');ctx.listen(form,'submit',event=>{event.preventDefault();const out=ctx.root.querySelector('[data-entry-error]');try{const raw=Object.fromEntries(new FormData(form).entries());raw.freezeSelection=form.elements.freezeSelection.checked;ctx.services.uiEntry.addLiquify(raw,boundToken(bound));ctx.services.dialogs.close();}catch(e){out.textContent=errorOf(e);}});bindClose(ctx);
}};}
export function createEntryAdvancedTransformDialogModule({mode='skew'}={}){return{id:`ui-entry-003.dialog.transform.${mode}.v1`,slot:'dialogs.content',mount(ctx){
  const bound=captureTarget(ctx,'transform');ctx.root.innerHTML=frame('進階變形',`<form><p>${escapeText(mode)}</p><label>A<input name="a" type="number" step=".1" value="10"></label><label>B<input name="b" type="number" step=".1" value="0"></label>${actions('套用')}</form>`);const form=ctx.root.querySelector('form');ctx.listen(form,'submit',event=>{event.preventDefault();const out=ctx.root.querySelector('[data-entry-error]');try{ctx.services.uiEntry.advancedTransform(mode,Object.fromEntries(new FormData(form).entries()),boundToken(bound));ctx.services.dialogs.close();}catch(e){out.textContent=errorOf(e);}});bindClose(ctx);
}};}
export function createEntryVectorFillDialogModule({kind='gradient'}={}){return{id:`ui-entry-003.dialog.vector-${kind}.v1`,slot:'dialogs.content',mount(ctx){
  const bound=captureTarget(ctx,kind==='gradient'?'vector-gradient':'vector-pattern');const body=kind==='gradient'?'<label>起點色<input name="start" type="color" value="#202020"></label><label>終點色<input name="end" type="color" value="#ffffff"></label><label>透明度<input name="opacity" type="number" min="0" max="1" step=".05" value="1"></label>':'<label>圖樣資源<input name="patternRef" required></label><label>縮放<input name="scale" type="number" step=".1" value="1"></label><label>旋轉角度<input name="rotation" type="number" value="0"></label>';
  ctx.root.innerHTML=frame(kind==='gradient'?'向量漸層':'向量圖樣',`<form>${body}${actions('套用')}</form>`);const form=ctx.root.querySelector('form');ctx.listen(form,'submit',event=>{event.preventDefault();const out=ctx.root.querySelector('[data-entry-error]');try{ctx.services.uiEntry.vectorFill(kind,Object.fromEntries(new FormData(form).entries()),boundToken(bound));ctx.services.dialogs.close();}catch(e){out.textContent=errorOf(e);}});bindClose(ctx);
}};}
export function createEntryFilterGalleryDialogModule({target='auto',layerId=null}={}){return{id:`ui-entry-003.dialog.filter-gallery.${target}.v1`,slot:'dialogs.content',mount(ctx){
  const bound=captureTarget(ctx,target==='layer'?'layer-filter':target==='image'?'filter-image':'filter-auto',{layerId});const filters=ctx.services.uiEntry.filterDescriptors();ctx.root.innerHTML=frame('濾鏡收藏館',`<div data-filter-gallery>${filters.map(item=>`<button type="button" data-filter="${escapeText(item.id)}"><strong>${escapeText(filterLabel(item.id,item.name))}</strong><span>${escapeText(filterGroupLabel(item.group))}</span></button>`).join('')}</div><p data-entry-error role="status"></p><div class="mui-b-dialog-actions">${close}</div>`);ctx.listen(ctx.root,'click',event=>{const type=event.target.closest?.('[data-filter]')?.dataset.filter;if(!type)return;const out=ctx.root.querySelector('[data-entry-error]');try{if(target==='layer')ctx.services.uiEntry.layerFilter(layerId,type,null,boundToken(bound));else ctx.services.uiEntry.addFilter(type,null,target,boundToken(bound));ctx.services.dialogs.close();}catch(e){out.textContent=errorOf(e);}});bindClose(ctx);
}};}
export function createEntryImageStackDialogModule(){return{id:'ui-entry-003.dialog.image-stack.v1',slot:'dialogs.content',mount(ctx){
  const bound=captureTarget(ctx,'image-stack');let targetToken=null;const render=()=>{let state;try{state=ctx.services.uiEntry.imageStack(boundToken(bound,targetToken));}catch(e){ctx.root.innerHTML=frame('影像 Filter Stack',`<p data-entry-error>${escapeText(errorOf(e))}</p><div class="mui-b-dialog-actions">${close}</div>`);return;}ctx.root.innerHTML=frame('影像 Filter Stack',`<div data-stack>${state.filters.length?state.filters.map((item,index)=>`<div><span>${escapeText(item.type||'filter')}</span><button type="button" data-move="${index}:-1">↑</button><button type="button" data-move="${index}:1">↓</button><button type="button" data-remove="${index}">×</button></div>`).join(''):'<p>目前沒有 Filter。</p>'}</div><p data-entry-error role="status"></p><div class="mui-b-dialog-actions">${close}</div>`);};
  ctx.listen(ctx.root,'click',event=>{const remove=event.target.closest?.('[data-remove]'),move=event.target.closest?.('[data-move]'),out=ctx.root.querySelector('[data-entry-error]');if(!remove&&!move)return;try{if(remove){const receipt=ctx.services.uiEntry.mutateImageFilterStack('remove',Number(remove.dataset.remove),0,boundToken(bound,targetToken));targetToken=receipt.targetToken;}else{const [index,delta]=move.dataset.move.split(':').map(Number),receipt=ctx.services.uiEntry.mutateImageFilterStack('move',index,delta,boundToken(bound,targetToken));targetToken=receipt.targetToken;}render();}catch(e){if(out)out.textContent=errorOf(e);}});bindClose(ctx);render();
}};}
export function createEntryShortcutsDialogModule(){return{id:'ui-entry-003.dialog.shortcuts.v1',slot:'dialogs.content',mount(ctx){ctx.root.innerHTML=frame('鍵盤快捷鍵','<div><p><kbd>V</kbd> Select</p><p><kbd>F</kbd> Fit</p><p><kbd>Ctrl+Z</kbd> Undo</p><p><kbd>Ctrl+Shift+Z</kbd> Redo</p><p><kbd>Delete</kbd> Delete selection</p><p><kbd>Space</kbd> temporary Pan</p></div><div class="mui-b-dialog-actions"><button type="button" data-entry-close>關閉</button></div>');bindClose(ctx);}};}
export function createEntryRecoveryDialogModule(){return{id:'ui-entry-003.dialog.recovery.v1',slot:'dialogs.content',mount(ctx){
  const alive=lifetime(ctx);const render=async()=>{ctx.root.innerHTML=frame('復原','<p>載入中…</p>');try{const items=await ctx.services.uiEntry.recoveryList();if(!alive())return;ctx.root.innerHTML=frame('復原',`${items.length?items.map(item=>`<div><span><strong>${escapeText(item.source)}</strong> · ${item.valid?(item.verified?'已驗證':'舊版／未驗證'):'無效'}${item.reason?' · '+escapeText(item.reason):''}</span><button type="button" data-recovery-source="${escapeText(item.source)}" data-recovery-token="${escapeText(item.token)}" ${item.valid?'':'disabled'}>復原</button></div>`).join(''):'<p>沒有可用的復原記錄。</p>'}<p data-entry-error role="status"></p><div class="mui-b-dialog-actions">${close}</div>`);}catch(e){ctx.root.innerHTML=frame('復原',`<p data-entry-error>${escapeText(errorOf(e))}</p><div class="mui-b-dialog-actions">${close}</div>`);}};
  ctx.listen(ctx.root,'click',async event=>{const button=event.target.closest?.('[data-recovery-source]');if(!button)return;const out=ctx.root.querySelector('[data-entry-error]');try{if(!globalThis.confirm?.(`Restore ${button.dataset.recoverySource}? Current unsaved view will be replaced.`))return;await ctx.services.uiEntry.restoreRecovery(button.dataset.recoverySource,button.dataset.recoveryToken);ctx.services.dialogs.close();}catch(e){if(out)out.textContent=errorOf(e);}});bindClose(ctx);void render();
}};}
