import { booleanPaths, createAnchor, createPath, createRepeat, dividePaths, drawVectorObject, expandRepeat, flattenSubpath, importSVGPaths, pathBounds, pointInRing, repeatTransforms, tracePath, vectorObjectToSVG } from './vector/vector-core.js';
import { IMAGE_CAPABILITIES, colorRasterToRgba8, createAdjustment, createFilter, createImageSnapshot, createLayerManifest, createVectorMask, renderImageStack, applyLayerEffects, reorderStack } from './image/image-core.js';
import { ActionDispatcher, COMMON_FLOWER_RECIPE, ExternalAssetAdapterRegistry, RECIPE_CAPABILITIES, RecipeEditor, RecipeEngine, installDefaultFlowerSchema, installProgramImportSchema } from './recipe/recipe-engine.js';
import { BrushPresetRegistry, DrawingGapFrequencyRanking, PAINT_CAPABILITIES, StrokeSessionRecorder, drawStrokeReplay, evaluateStrokeQuality, exportBrushPackage, importDrawingWorkflow, replayStrokeSession, strokeBoundingBox } from './paint/paint-core.js';
import { importBrushPackage } from './paint/brush-engine.js';
import { StylusTestRecorder } from './input/stylus-test.js';
import { CalibrationProfileStore } from './input/device-validation.js';
import { BrowserInteractiveBenchmark } from './render/interactive-benchmark.js';
import { PressureCurveEditor } from './paint/stroke-quality-tools.js';
import { NaturalMediaStateMap } from './paint/natural-media-state.js';
import { ExternalReferenceRunnerRegistry, GapFrequencyRanking, attachReferencePackage, compareReference, createFirstPartyProgramImporter, createManualReferenceRunKit, createReferencePackage, validateReferencePackage } from './program-import/index.js';
import { installAICommandLayer } from './ai/install-ai.js';

const clone=v=>JSON.parse(JSON.stringify(v)),id=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const M={identity:()=>[1,0,0,1,0,0],translate:(x,y)=>[1,0,0,1,x,y],rotate:a=>{a=a*Math.PI/180;return[Math.cos(a),Math.sin(a),-Math.sin(a),Math.cos(a),0,0]},multiply:(a,b)=>[a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]],point:(m,p)=>({x:m[0]*p.x+m[2]*p.y+m[4],y:m[1]*p.x+m[3]*p.y+m[5]})};

export function paintSessionWorldBounds(object,parent=M.identity()){
  const dabs=(object?.replay?.strokes||[]).flatMap(stroke=>stroke?.dabs||stroke?.points||[]);
  if(!dabs.length)return null;
  // drawStrokeReplay paints every dab inside its size-radius circle; this is a
  // conservative visual footprint for elliptical/texture dabs and stays valid
  // after the object's full affine world transform.
  const local=strokeBoundingBox(dabs);
  const effective=M.multiply(parent,object.matrix||M.identity());
  const corners=[
    {x:local.x,y:local.y},
    {x:local.x+local.width,y:local.y},
    {x:local.x+local.width,y:local.y+local.height},
    {x:local.x,y:local.y+local.height}
  ].map(point=>M.point(effective,point));
  const xs=corners.map(point=>point.x),ys=corners.map(point=>point.y);
  return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)};
}

const oval=(cx,cy,rx,ry,role,name,matrix=M.identity())=>{const k=.5522847498;return createPath({id:id(role),name,fill:'#e5a0a5',stroke:'#6b3d47',strokeWidth:1.4,matrix:M.multiply(M.translate(cx,cy),matrix),subpaths:[{role:'outer',closed:true,anchors:[createAnchor(rx,0,{x:0,y:-ry*k},{x:0,y:ry*k}),createAnchor(0,ry,{x:rx*k,y:0},{x:-rx*k,y:0}),createAnchor(-rx,0,{x:0,y:ry*k},{x:0,y:-ry*k}),createAnchor(0,-ry,{x:-rx*k,y:0},{x:rx*k,y:0})]}],metadata:{role}});};
const petal=(cx,cy,length,width,angle,index)=>{const path=createPath({id:id('petal'),name:`Petal ${index+1}`,fill:'#dc8994',stroke:'#653842',strokeWidth:1.3,matrix:M.multiply(M.translate(cx,cy),M.rotate(angle)),subpaths:[{role:'outer',closed:true,anchors:[createAnchor(0,0,{x:-width*.16,y:0},{x:width*.16,y:0}),createAnchor(width*.45,-length*.48,{x:0,y:length*.22},{x:0,y:-length*.25}),createAnchor(0,-length,{x:width*.28,y:length*.12},{x:-width*.28,y:length*.12}),createAnchor(-width*.45,-length*.48,{x:0,y:-length*.25},{x:0,y:length*.22})]}],metadata:{role:'petal',index}});return{path,role:'petal'};};
const leaf=(cx,cy,length,width,angle,index)=>{const path=createPath({id:id('leaf'),name:`Leaf ${index+1}`,fill:'#64835c',stroke:'#31513b',strokeWidth:1.2,matrix:M.multiply(M.translate(cx,cy),M.rotate(angle)),subpaths:[{role:'outer',closed:true,anchors:[createAnchor(0,0,{x:-width*.12,y:0},{x:width*.12,y:0}),createAnchor(width*.5,-length*.52,{x:0,y:length*.22},{x:0,y:-length*.28}),createAnchor(0,-length,{x:width*.25,y:length*.15},{x:-width*.25,y:length*.15}),createAnchor(-width*.5,-length*.52,{x:0,y:-length*.28},{x:0,y:length*.22})]}],metadata:{role:'leaf',index}});return{path,role:'leaf'};};
const stem=(cx,cy,height,width=14,angle=0)=>{const path=createPath({id:id('stem'),name:'Stem',fill:'#48684d',stroke:'#294936',strokeWidth:1,matrix:M.multiply(M.translate(cx,cy),M.rotate(angle)),subpaths:[{role:'outer',closed:true,anchors:[createAnchor(-width/2,0),createAnchor(width/2,0),createAnchor(width*.35,height),createAnchor(-width*.35,height)]}],metadata:{role:'stem'}});return{path,role:'stem'};};
const center=(cx,cy,r)=>{const path=oval(cx,cy,r,r*.9,'center','Flower Center');return{path,role:'center'};};
const wrap=entry=>({id:`region_${entry.path.id}`,name:entry.path.name,role:entry.role,path:entry.path,metadata:{role:entry.role}});

export function createFlowerSkeleton(kind='radial'){
  const inputs=[];if(kind==='radial'){for(let i=0;i<8;i++)inputs.push(petal(0,0,132,66,i*45,i));inputs.push(center(0,0,34));inputs.push(leaf(-38,150,126,55,-36,0),leaf(36,154,112,50,32,1),stem(0,40,190,13));}
  else if(kind==='layered'){for(let i=0;i<11;i++)inputs.push(petal(0,10,138,72,i*360/11,i));for(let i=0;i<7;i++)inputs.push(petal(0,4,93,54,i*360/7+14,i+11));inputs.push(center(0,0,29));inputs.push(leaf(-55,155,135,64,-43,0),leaf(52,148,118,58,37,1),stem(0,50,190,14));}
  else if(kind==='side'){for(let i=0;i<6;i++)inputs.push(petal(0,-45,116-i*7,58,212+i*22,i));inputs.push(center(-4,-48,22));inputs.push(leaf(-18,125,122,50,-70,0),stem(0,-10,235,12,3));}
  else if(kind==='trumpet'){for(let i=0;i<6;i++)inputs.push(petal(0,-58,105,55,i*60,i));const bell=createPath({id:id('petal'),name:'Trumpet Bell',fill:'#d9878e',stroke:'#673943',strokeWidth:1.4,matrix:M.translate(0,15),subpaths:[{role:'outer',closed:true,anchors:[createAnchor(-38,0),createAnchor(-92,-78,{x:20,y:20},{x:-20,y:-22}),createAnchor(0,-128,{x:-38,y:0},{x:38,y:0}),createAnchor(92,-78,{x:20,y:-22},{x:-20,y:20}),createAnchor(38,0)]}],metadata:{role:'petal'}});inputs.push({path:bell,role:'petal'},center(0,-60,24),leaf(-45,140,132,58,-46,0),leaf(36,158,104,44,35,1),stem(0,0,222,13));}
  else {const positions=[[-95,-45,36],[-42,-86,22],[22,-64,-18],[77,-22,-42],[-58,5,58],[18,22,8],[88,48,-35]];positions.forEach(([x,y,a],i)=>{for(let j=0;j<3+(i%3);j++)inputs.push(petal(x,y,52+(i%2)*12,28,j*360/(3+i%3)+a,i*5+j));});inputs.push(leaf(-42,152,132,58,-52,0),leaf(52,166,105,48,48,1),stem(-15,20,235,11,-8));}
  return{kind,name:{radial:'放射對稱單層花',layered:'多層重疊花',side:'側視花',trumpet:'喇叭形花',asymmetric:'不對稱花序'}[kind]||kind,inputs:inputs.map(wrap)};
}

export function installRenderer(app){const renderer=app.renderer,originalDraw=renderer.drawObject.bind(renderer),originalBounds=renderer.objectWorldBounds.bind(renderer),originalLayer=renderer.drawLayerObjects.bind(renderer),originalSVG=app.objectToSVG.bind(app),originalSelection=renderer.drawSelectionOverlay.bind(renderer),originalDrawImage=renderer.drawImage.bind(renderer);renderer.studioImageCache=new Map();renderer.studioLayerCache=new Map();
  renderer.drawObject=function(ctx,o,options={}){if(o.visible===false)return;if(o.type==='path'||o.type==='repeat'){ctx.save();if(o.blendMode)ctx.globalCompositeOperation=o.blendMode;ctx.transform(...(o.matrix||M.identity()));ctx.globalAlpha*=o.opacity??1;if(o.mask?.path){tracePath(ctx,o.mask.path);ctx.clip(o.mask.path.fillRule||'evenodd');}drawVectorObject(ctx,o,{document:app.doc,drawObject:(c,child)=>renderer.drawObject(c,child,{...options,page:options.page||app.page()})});ctx.restore();return;}if(o.type==='paint-session'){ctx.save();ctx.transform(...(o.matrix||M.identity()));ctx.globalAlpha*=o.opacity??1;drawStrokeReplay(ctx,o.replay);ctx.restore();return;}if(o.type==='image'&&((o.adjustments||[]).length||(o.filterStack||[]).length||(o.effects||[]).length||o.rasterMask||o.rasterState?.colorRaster)){ctx.save();if(o.blendMode&&IMAGE_CAPABILITIES.blendModes.includes(o.blendMode))ctx.globalCompositeOperation=o.blendMode;if(o.mask?.path){tracePath(ctx,o.mask.path);ctx.clip(o.mask.path.fillRule||'evenodd');}const m=o.matrix||M.identity();ctx.transform(...m);ctx.globalAlpha*=o.opacity??1;renderer.drawImage(ctx,o);ctx.restore();return;}return originalDraw(ctx,o,options);};
  renderer.drawImage=function(ctx,o){
    const hasStack=(o.adjustments||[]).length||(o.filterStack||[]).length||(o.effects||[]).length||o.rasterMask;
    const hasRasterState=Boolean(o.rasterState?.colorRaster);
    if(!hasStack&&!hasRasterState)return originalDrawImage(ctx,o);
    const key=JSON.stringify([o.id||o.src,hasRasterState?app.doc.modifiedAt:null,hasRasterState?'raster-state':o.src,o.adjustments,o.filterStack,o.effects,o.rasterMask]);
    let canvas=renderer.studioImageCache.get(key);
    if(!canvas){
      let sourceImageData=null;
      if(hasRasterState){
        const preview=colorRasterToRgba8(o.rasterState.colorRaster,{icc:o.rasterState.icc||null});
        renderer.lastColorDiagnostic={objectId:o.id,status:preview.status,reason:preview.reason||null,sourceBitDepth:preview.sourceBitDepth||null,colorMode:preview.colorMode||o.rasterState.colorRaster.colorMode};
        if(preview.status!=='ok'){console.warn('INK color render unsupported',renderer.lastColorDiagnostic);return originalDrawImage(ctx,o);}
        sourceImageData=preview.imageData;
      }else{
        const img=renderer.getImage(o.src);
        if(!img?.complete||!img.naturalWidth)return originalDrawImage(ctx,o);
        const raw=document.createElement('canvas');raw.width=Math.min(4096,img.naturalWidth);raw.height=Math.min(4096,img.naturalHeight);
        const rc=raw.getContext('2d',{willReadFrequently:true});rc.drawImage(img,0,0,raw.width,raw.height);sourceImageData=rc.getImageData(0,0,raw.width,raw.height);
      }
      canvas=document.createElement('canvas');canvas.width=sourceImageData.width;canvas.height=sourceImageData.height;
      const c=canvas.getContext('2d',{willReadFrequently:true});
      try{
        const processed=applyLayerEffects(renderImageStack(sourceImageData,{adjustments:o.adjustments||[],filters:o.filterStack||[],mask:o.rasterMask||null}),o.effects||[]);
        c.putImageData(new ImageData(processed.data,processed.width,processed.height),0,0);
      }catch(error){console.warn('INK image stack fallback',error);c.putImageData(new ImageData(sourceImageData.data,sourceImageData.width,sourceImageData.height),0,0);}
      renderer.studioImageCache.set(key,canvas);while(renderer.studioImageCache.size>16)renderer.studioImageCache.delete(renderer.studioImageCache.keys().next().value);
    }
    ctx.drawImage(canvas,0,0,o.w||canvas.width,o.h||canvas.height);
  };
  renderer.drawLayerObjects=function(ctx,layer,page,options={}){const adjustments=layer.adjustments||[],filters=layer.filterStack||[],effects=layer.effects||[],mask=layer.mask||layer.groupMask||layer.clippingMask;if(adjustments.length||filters.length||effects.length||mask?.type==='raster-mask'){const transform=ctx.getTransform(),key=JSON.stringify([layer.id,app.doc.modifiedAt,ctx.canvas.width,ctx.canvas.height,[transform.a,transform.b,transform.c,transform.d,transform.e,transform.f],adjustments,filters,effects,mask]);let output=app.doc.components?.definitions?.length?null:renderer.studioLayerCache.get(key);if(!output){const raw=document.createElement('canvas');raw.width=ctx.canvas.width;raw.height=ctx.canvas.height;const rc=raw.getContext('2d',{willReadFrequently:true});rc.setTransform(transform);rc.globalAlpha=ctx.globalAlpha;if(mask?.path){rc.save();rc.transform(...(mask.path.matrix||M.identity()));tracePath(rc,mask.path);rc.restore();rc.clip(mask.path.fillRule||'evenodd');}originalLayer(rc,layer,page,options);try{const pixels=rc.getImageData(0,0,raw.width,raw.height),processed=applyLayerEffects(renderImageStack(pixels,{adjustments,filters,mask:mask?.type==='raster-mask'?mask:null}),effects);rc.setTransform(1,0,0,1,0,0);rc.clearRect(0,0,raw.width,raw.height);rc.putImageData(new ImageData(processed.data,processed.width,processed.height),0,0);}catch(error){console.warn('INK layer stack fallback',error);}output=raw;renderer.studioLayerCache.set(key,output);while(renderer.studioLayerCache.size>10)renderer.studioLayerCache.delete(renderer.studioLayerCache.keys().next().value);}ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.globalCompositeOperation=layer.blendMode||'source-over';ctx.drawImage(output,0,0);ctx.restore();return;}ctx.save();if(layer.blendMode)ctx.globalCompositeOperation=layer.blendMode;if(mask?.path){ctx.save();ctx.transform(...(mask.path.matrix||M.identity()));tracePath(ctx,mask.path);ctx.restore();ctx.clip(mask.path.fillRule||'evenodd');}originalLayer(ctx,layer,page,options);ctx.restore();};
  renderer.objectWorldBounds=function(o,parent=M.identity()){if(o.type==='path'){const effective=M.multiply(parent,o.matrix||M.identity());return pathBounds(o,effective);}if(o.type==='paint-session'){return paintSessionWorldBounds(o,parent)||originalBounds(o,parent);}if(o.type==='repeat'){let b=null;for(const t of repeatTransforms(o)){const child=clone(o.source);child.matrix=M.multiply(t,child.matrix||M.identity());const cb=renderer.objectWorldBounds(child,M.multiply(parent,o.matrix||M.identity()));b=b?{x:Math.min(b.x,cb.x),y:Math.min(b.y,cb.y),w:Math.max(b.x+b.w,cb.x+cb.w)-Math.min(b.x,cb.x),h:Math.max(b.y+b.h,cb.y+cb.h)-Math.min(b.y,cb.y)}:cb;}return b||{x:0,y:0,w:1,h:1};}return originalBounds(o,parent);};
  app.objectToSVG=function(o){if(o.visible===false)return'';if(['path','repeat'].includes(o.type)){const defs=[];const body=vectorObjectToSVG(o,defs);return(defs.length?`<defs>${defs.join('')}</defs>`:'')+body;}return originalSVG(o);};
  renderer.drawSelectionOverlay=function(ctx){originalSelection(ctx);if(!app.studio?.pathEdit)return;const found=app.selectedObjects().find(x=>x.object.type==='path');if(!found)return;const path=found.object,m=path.matrix||M.identity();ctx.save();ctx.setTransform(renderer.dpr,0,0,renderer.dpr,0,0);for(const sub of path.subpaths||[])for(let i=0;i<(sub.anchors||[]).length;i++){const a=sub.anchors[i],world=M.point(m,a),s=renderer.worldToScreen(world);ctx.fillStyle=i===app.studio.nodeIndex?'#d08a28':'#fff';ctx.strokeStyle='#236b63';ctx.lineWidth=1.4;ctx.fillRect(s.x-4,s.y-4,8,8);ctx.strokeRect(s.x-4,s.y-4,8,8);}ctx.restore();};
  const originalHit=app.hitObject.bind(app);app.hitObject=function(o,world,parent=M.identity()){if(o.type==='path'){const inv=((m)=>{const d=m[0]*m[3]-m[1]*m[2]||1;return[m[3]/d,-m[1]/d,-m[2]/d,m[0]/d,(m[2]*m[5]-m[3]*m[4])/d,(m[1]*m[4]-m[0]*m[5])/d]})(o.matrix||M.identity()),p=M.point(inv,world);let inside=false;for(const sub of o.subpaths||[]){const hit=pointInRing(p,flattenSubpath(sub));if(sub.role==='hole'&&hit)inside=false;else if(hit)inside=true;}return inside;}return originalHit(o,world,parent);};
}

function downloadJSON(app,value,name){app.download(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),name);}
function status(message,state='pass'){return Object.freeze({message:String(message||''),state});}

export function installStudioCore(app){
  const engine=new RecipeEngine({app});installDefaultFlowerSchema(engine);installProgramImportSchema(engine);engine.registerRecipe(COMMON_FLOWER_RECIPE);let brushes=new BrushPresetRegistry();const dispatcher=new ActionDispatcher(engine),externalAssets=new ExternalAssetAdapterRegistry(),programImporter=createFirstPartyProgramImporter({inkVersion:'1.6.0'}),referenceRunners=new ExternalReferenceRunnerRegistry(),gapRanking=new GapFrequencyRanking(),drawingGaps=new DrawingGapFrequencyRanking(),calibrationProfiles=new CalibrationProfileStore({storage:globalThis.localStorage}),stylusRecorder=new StylusTestRecorder({deviceInfo:{userAgent:navigator.userAgent,platform:navigator.platform,maxTouchPoints:navigator.maxTouchPoints},calibrationProfile:calibrationProfiles.active()}),interactiveBenchmark=null;installRenderer(app);const studio=app.studio={engine,dispatcher,brushes,externalAssets,programImporter,referenceRunners,gapRanking,drawingGaps,stylusRecorder,calibrationProfiles,interactiveBenchmark,recipe:COMMON_FLOWER_RECIPE,pathEdit:false,nodeIndex:0,currentFixture:null,lastExecutionId:null,lastPaintSession:null,lastProgramImport:null,lastProgramReplay:null,lastDifference:null,lastReferenceRun:null,lastReferencePackage:null,lastDrawingImport:null,lastDrawingReplay:null,lastDrawingQuality:null,activeStrokeRecorder:null,lastStylusReport:null,lastInteractiveBenchmark:null,programStep:0};
  const reloadBrushPackages=()=>{const restored=new BrushPresetRegistry();for(const pack of app.doc.brushPackages||[]){const result=importBrushPackage(pack,restored);if(result.status==='REJECTED')throw new Error(`INK_BRUSH_PACKAGE_INVALID:${result.errors.join(',')}`);}brushes=restored;studio.brushes=restored;return restored;};
  studio.reloadBrushPackages=reloadBrushPackages;
  const importBrushPackageToDocument=raw=>{const pack=typeof raw==='string'?JSON.parse(raw):clone(raw),candidate=new BrushPresetRegistry();for(const existing of app.doc.brushPackages||[])importBrushPackage(existing,candidate);const result=importBrushPackage(pack,candidate);if(result.status==='REJECTED')throw new Error(`INK_BRUSH_PACKAGE_INVALID:${result.errors.join(',')}`);app.history.pushScoped('匯入 Brush Package',[['brushPackages']],()=>{app.doc.brushPackages=app.doc.brushPackages||[];app.doc.brushPackages.push(pack);});brushes=candidate;studio.brushes=candidate;return result;};
  reloadBrushPackages();
  const loadFixture=kind=>{const fixture=createFlowerSkeleton(kind),page=app.page();page.layers=[{id:id('layer'),name:'Recipe Input',kind:'regions',visible:true,locked:false,opacity:1,objects:[]}];page.activeLayerId=page.layers[0].id;page.regions=fixture.inputs;app.selection=[];studio.currentFixture=fixture;app.doc.title=`INK ${fixture.name}`;app.history.clear();app.spatialDirty=true;app.refreshAll();app.resetView();status(`${fixture.name}：${fixture.inputs.length} 個結構區域已載入`);return fixture;};
  const execute=(options={})=>{if(!studio.currentFixture)loadFixture(options.fixtureKind||'radial');app.history.begin(`Recipe ${COMMON_FLOWER_RECIPE.name}`);try{const parameters={fillHue:options.parameters?.fillHue||'#cf6e82',texture:Number(options.parameters?.texture??14),contrast:Number(options.parameters?.contrast??8)};const report=engine.execute(COMMON_FLOWER_RECIPE.id,{document:app.doc,inputs:studio.currentFixture.inputs,parameters,...options});app.history.commit();studio.lastExecutionId=report.id;app.spatialDirty=true;app.refreshAll();app.fitContent();status(`Recipe 完成 · ${report.states.length} 狀態 · ${report.warnings.length} warning · ${report.result.documentHash}`);return report;}catch(e){app.history.cancel();status(`Recipe 拒絕／回滾：${e.message}`,'fail');throw e;}};
  const selectedPaths=()=>app.selectedObjects().map(x=>x.object).filter(o=>o.type==='path');
  const doBoolean=operation=>{const paths=selectedPaths();if(paths.length<2)throw new Error('請先選取至少兩個 Path');const layer=app.layer();app.history.pushScoped(`Boolean ${operation}`,[app.layerObjectsPath(layer)],()=>{const result=operation==='divide'?dividePaths(paths,{name:'Divide result'}):booleanPaths(paths,operation,{name:`${operation} result`});layer.objects=layer.objects.filter(o=>!paths.includes(o));if(result.type==='group')layer.objects.push(...result.children);else layer.objects.push(result);const created=result.type==='group'?result.children:[result];app.selection=created.map(object=>({layerId:layer.id,objectId:object.id}));});app.spatialDirty=true;app.refreshAll();status(`Boolean ${operation} 已產生可編輯 Compound Path`);};
  const addVectorMask=()=>{const paths=selectedPaths();if(!paths[0])throw new Error('請先選取 Path');const found=app.selectedObjects().find(item=>item.object===paths[0]);app.history.pushScoped('加入 Path 遮罩',[app.objectPath(found)],()=>{paths[0].mask=createVectorMask(paths[0],{invert:false,feather:0,expand:0});});app.renderer.render();app.refreshAll();status('物件 Mask 已依真實 Path 邊界運作');return paths[0].mask;};
  const addRepeat=(mode,options={})=>{const source=selectedPaths()[0];if(!source)throw new Error('請先選取一個 Path');const layer=app.layer(),count=mode==='mirror'?2:Number(options.count??8);app.history.pushScoped(`建立 ${mode}`,[app.layerObjectsPath(layer)],()=>{const r=createRepeat(source,{mode,count,center:options.center||{x:0,y:0},axis:options.axis||'y',dx:Number(options.dx??82),dy:Number(options.dy??82),columns:Number(options.columns??3),rows:Number(options.rows??3)});layer.objects.push(r);app.selection=[{layerId:layer.id,objectId:r.id}];});app.spatialDirty=true;app.refreshAll();status(`${mode} 已渲染全部實例`);return true;};
  const expand=()=>{const found=app.selectedObjects().find(x=>x.object.type==='repeat');if(!found)throw new Error('請先選取 Repeat');app.history.pushScoped('展開 Repeat',[app.layerObjectsPath(found.layer)],()=>{const group=expandRepeat(found.object);found.layer.objects.splice(found.index,1,...group.children);app.selection=group.children.map(o=>({layerId:found.layer.id,objectId:o.id}));});app.spatialDirty=true;app.refreshAll();status('Repeat 已展開，每個 Path 可獨立編輯');};
  const visualDemo=type=>{loadFixture(type==='recipe2'?'side':'layered');execute();const petalLayer=app.page().layers.find(l=>l.name==='Flower · Petals');if(type==='boolean'&&petalLayer){app.selection=petalLayer.objects.slice(0,3).map(o=>({layerId:petalLayer.id,objectId:o.id}));doBoolean('union');}if(type==='repeat'&&petalLayer){app.selection=[{layerId:petalLayer.id,objectId:petalLayer.objects[0].id}];addRepeat('radial');}if(type==='mask'&&petalLayer){petalLayer.mask=createVectorMask(petalLayer.objects[0],{feather:1});status('Layer Mask 與 Path 邊界已啟用');app.renderer.render();}if(type==='adjustment'&&petalLayer){petalLayer.adjustments=[createAdjustment('brightnessContrast',{brightness:12,contrast:22}),createAdjustment('hueSaturation',{hue:-8,saturation:18})];status('Adjustment Stack 已非破壞套用');app.renderer.render();}if(type==='filter'&&petalLayer){petalLayer.filterStack=[createFilter('gaussianBlur',{radius:.6}),createFilter('sharpen',{amount:1}),createFilter('textureOverlay',{amount:18,scale:6,seed:31})];status('Filter Stack 已套用並可重排');app.renderer.render();}return true;};
  const createPaintDemo=()=>{const recorder=new StrokeSessionRecorder({id:id('paint-session'),name:'完整花卉筆刷測試',seed:1001,registry:brushes}),specs=[{brushId:'opaque-paint',color:'#d86d86',points:[[-115,-20,.25],[-60,-90,.78],[0,-132,.94],[60,-90,.76],[115,-20,.28]]},{brushId:'watercolor',color:'#75925d',points:[[-38,55,.3],[-88,118,.75],[-52,190,.42]]},{brushId:'dry-brush',color:'#496944',points:[[32,58,.32],[92,126,.8],[58,195,.36]]},{brushId:'soft-paint',color:'#f2c5b5',points:[[-76,-22,.2],[0,-58,.5],[78,-18,.18]]}];for(const [index,spec]of specs.entries()){recorder.beginStroke({id:id('paint'),brushId:spec.brushId,color:spec.color,seed:1001+index,metadata:{region:['petal','leaf','leaf','light'][index]}});spec.points.forEach(([x,y,pressure],i)=>recorder.addSample({x,y,pressure,time:i*24,tiltX:i*8-12,tiltY:18-i*3,azimuth:i*.4}));recorder.endStroke();}const session=recorder.finish({coverage:['flower-crown','leaves','light-shadow']}),replay=replayStrokeSession(session,{registry:brushes}),object={id:session.id,type:'paint-session',name:session.name,matrix:M.identity(),opacity:1,session,replay};const layer=app.layer();app.history.pushScoped('建立 Stroke Session',[app.layerObjectsPath(layer)],()=>layer.objects.push(object));studio.lastPaintSession=session;app.spatialDirty=true;app.refreshAll();app.fitContent();status(`Stroke Session 完成 · ${session.strokes.length} 筆 · ${replay.replayHash}`);return object;};
  const renderProgramReport=report=>report;
  const translateProgram=()=>{if(!studio.lastProgramImport)throw new Error('尚未匯入程序資產');const report=programImporter.translate(studio.lastProgramImport.id);studio.lastProgramImport=report;engine.registerRecipe(report.recipe);studio.programStep=0;gapRanking.add({program:report.program,conversionReport:report.conversionReport,assetTypes:[report.detection.format]});renderProgramReport(report);status(`已編譯 ${report.recipe.steps.length} 個 Recipe 步驟；${report.unsupportedOperations.length} 個缺口明確保留`,report.status==='COMPILED'?'pass':'fail');return report;};
  const programInputs=()=>app.selectedObjects().map(item=>({id:item.object.id,name:item.object.name,role:'target',path:item.object.type==='path'?item.object:undefined,object:item.object,metadata:{role:'target'}}));
  const assertProgramExecutionAllowed=report=>{if(!report)throw new Error('程序尚未匯入');const wholeSourceRejected=report.workflowIR?.metadata?.sourceCoverage?.wholeSourceRejected===true;if(report.status==='REJECTED'||report.executionAllowed===false||wholeSourceRejected)throw Object.assign(new Error('INK_IMPORT_EXECUTION_REJECTED'),{code:'INK_IMPORT_EXECUTION_REJECTED'});return report;};
  const runProgram=(options={})=>{const report=studio.lastProgramImport;assertProgramExecutionAllowed(report);if(!report.recipe)throw new Error('程序尚未編譯為 Recipe');const needsTarget=report.recipe.steps.some(step=>step.role==='target'),inputs=programInputs();if(needsTarget&&!inputs.length)throw new Error('此程序需要先選取 Path／Object');engine.registerRecipe(report.recipe);const before=clone(app.doc);app.history.begin(`外部程序 Recipe · ${report.metadata.name}`);try{const replay=engine.execute(report.recipe.id,{document:app.doc,inputs,...options});studio.lastProgramReplay=replay;studio.lastExecutionId=replay.id;studio.lastDifference=compareReference({reference:before,ink:app.doc,kind:'vector',metadata:{comparisonType:'INK_BEFORE_AFTER',sameInputConfirmed:true}});const coverage=programImporter.coverage(report.id,{replayReport:replay,differenceReport:studio.lastDifference});const stored=programImporter.attachToDocument(report.id,app.doc);stored.replayReport=replay;stored.coverageReport=coverage;stored.differenceReport=studio.lastDifference;const saved=app.doc.programAssets.find(item=>item.id===stored.id);if(saved)Object.assign(saved,{replayReport:replay,coverageReport:coverage,differenceReport:studio.lastDifference});app.history.commit();app.spatialDirty=true;app.refreshAll();app.fitContent();status(`試跑完成 · ${replay.states.length} steps · Coverage ${Math.round(coverage.metrics.overallCompatibility*100)}% · ${coverage.decision}`,coverage.complete?'pass':'fail');return{replay,coverage,difference:studio.lastDifference};}catch(error){app.history.cancel({restore:true});app.refreshAll();status(`試跑失敗且已回滾：${error.message}`,'fail');throw error;}};
  const readableProgramFileExtensions=new Set(['txt','md','markdown','json','jsx','js']);
  const programFileExtension=file=>String(file?.name||'').toLowerCase().match(/\.([^.]+)$/)?.[1]||'';
  const programFileImportSource=async file=>{const bytes=new Uint8Array(await file.arrayBuffer()),extension=programFileExtension(file);if(!readableProgramFileExtensions.has(extension))return{bytes};try{return{text:new TextDecoder('utf-8',{fatal:true}).decode(bytes)};}catch(error){throw Object.assign(new Error('INK_PROGRAM_TEXT_UTF8_REQUIRED'),{code:'INK_PROGRAM_TEXT_UTF8_REQUIRED',cause:error});}};
  const importProgramFile=async(file,{licenseSpdx=null,sourceUrl=null,safetyMode='STATIC_PARSE'}={})=>{const source=await programFileImportSource(file),license=licenseSpdx?{spdx:String(licenseSpdx)}:{},provenance={localUserProvided:true,...(sourceUrl?{sourceUrl:String(sourceUrl)}:{})};const report=programImporter.importAsset({name:file.name,mimeType:file.type,...source,license,provenance,safetyMode,compile:safetyMode==='TRANSLATE_ONLY'});studio.lastProgramImport=report;studio.programStep=0;if(report.recipe)engine.registerRecipe(report.recipe);renderProgramReport(report);status(`程序資產 ${report.status} · ${report.detection.format} · ${report.security.status}`,report.status==='REJECTED'?'fail':'pass');return report;};
  const referenceRequest=(runnerId='manual')=>{const report=studio.lastProgramImport;if(!report)throw new Error('請先匯入程序資產');const software={photoshop:'Adobe Photoshop',illustrator:'Adobe Illustrator',inkscape:'Inkscape','gimp-krita':'GIMP／Krita','paint-session':'Paint Session'}[runnerId]||runnerId;return{assetId:report.id,runnerId,software,program:{name:report.metadata.name,format:report.detection.format,source:report.metadata.source},programVersion:report.metadata.version,input:{instruction:'使用與 INK 相同的指定輸入素材'}};};
  const buildManualReference=(options={})=>{const request=referenceRequest(options.runnerId||'manual'),kit=createManualReferenceRunKit(request,{instructions:['在指定原軟體開啟指定輸入素材','載入並執行程序資產','保存最終成品與中間狀態','匯出圖層、物件或筆畫結構摘要','將執行紀錄與軟體版本填入 Reference Evidence JSON'],requiredImports:['source output','source structure summary','source execution log','source application version']});studio.lastReferencePackage=kit;if(options.download===true)downloadJSON(app,kit,`${request.assetId}.manual-reference-kit.json`);status('人工基準包已建立；它可作正式證據，但不會被標示為自動 Runner');return kit;};
  const buildReferencePackage=()=>{const report=studio.lastProgramImport;if(!report)throw new Error('請先匯入程序資產');const files=Object.fromEntries(['asset.json','source-program','source-license','source-input','source-application-version','source-execution-log','source-intermediate-states','source-output','source-structure-summary','canonical-operations','ink-recipe','ink-document','ink-output','capability-report','gap-report','difference-report','replay-report','qa-report'].map(name=>[name,{assetId:report.id,embedded:true}]));const manifest=createReferencePackage({assetId:report.id,kind:report.detection.format,source:{referenceRun:studio.lastReferenceRun},ink:{recipe:report.recipe,replayReport:studio.lastProgramReplay},reports:{difference:studio.lastDifference,gap:gapRanking.report()},files,status:studio.lastDifference?.decision||'PARTIAL'});studio.lastReferencePackage=manifest;return manifest;};
  const strokeStatus=(message,state='partial')=>status(message,state);
  const activeBrushId=()=>{const kind=app.interaction?.object?.kind||app.toolSettings?.[app.tool]?.kind||app.tool;return kind==='pencil'?'pencil':kind==='marker'?'marker':kind==='drybrush'?'dry-brush':kind==='airbrush'?'soft-paint':kind==='brush'?'opaque-paint':'ink';};
  const beginStrokeRecording=()=>{if(studio.activeStrokeRecorder&&studio.activeStrokeRecorder.session.status!=='complete')throw new Error('Stroke Session 已在錄製');studio.activeStrokeRecorder=new StrokeSessionRecorder({id:id('stroke-session'),name:app.doc.title,seed:Date.now()>>>0,registry:brushes,documentState:{documentId:app.doc.id,pageId:app.page().id},layerState:app.page().layers.map(layer=>({id:layer.id,name:layer.name,visible:layer.visible,opacity:layer.opacity}))});strokeStatus('RECORDING · 請直接在主畫布使用滑鼠或觸控筆','pass');return studio.activeStrokeRecorder;};
  const toggleStrokeRecording=()=>{const recorder=studio.activeStrokeRecorder;if(!recorder)throw new Error('尚未開始錄製');if(recorder.session.status==='recording'){recorder.pause(performance.now());strokeStatus('PAUSED · 可繼續錄製');}else if(recorder.session.status==='paused'){recorder.resume(performance.now());strokeStatus('RECORDING · 已繼續','pass');}else throw new Error('Session 已結束');};
  const finishStrokeRecording=()=>{const recorder=studio.activeStrokeRecorder;if(!recorder)throw new Error('尚未開始錄製');const session=recorder.finish({source:'INK_MAIN_CANVAS',manualInput:true}),replay=replayStrokeSession(session,{registry:brushes}),quality=evaluateStrokeQuality(session,replay,{frameTimeMs:app.runtimeHealth?.diagnostics?.().frameTime?.p95||0,inputLatencyMs:app.penInput?.diagnostics?.().latency?.p95Ms||0});studio.lastPaintSession=session;studio.lastDrawingReplay=replay;studio.lastDrawingQuality=quality;app.history.pushScoped('保存 Stroke Session',[['strokeSessions'],['handDrawingReports']],()=>{app.doc.strokeSessions=app.doc.strokeSessions||[];app.doc.strokeSessions.push(session);app.doc.handDrawingReports=app.doc.handDrawingReports||[];app.doc.handDrawingReports.push(replay.report,quality);});strokeStatus(`COMPLETE · ${session.strokes.length} strokes · ${replay.replayHash}`,'pass');return session;};
  const importDrawingFile=async(file,{licenseSpdx='NOASSERTION',sourceUrl=null}={})=>{const report=importDrawingWorkflow({name:file.name,mimeType:file.type,text:await file.text(),license:{spdx:String(licenseSpdx||'NOASSERTION')},sourceUrl:sourceUrl?String(sourceUrl):null});studio.lastDrawingImport=report;drawingGaps.add(report);if(report.inkStrokeSession?.strokes?.length){studio.lastPaintSession=report.inkStrokeSession;studio.lastDrawingReplay=replayStrokeSession(report.inkStrokeSession,{registry:brushes});report.replayReport=studio.lastDrawingReplay.report;report.differenceReport={status:'REFERENCE_REQUIRED',manualArtQuality:'USER VALIDATION REQUIRED'};}app.history.pushScoped('保存手繪匯入報告',[['handDrawingReports'],['drawingGapRanking']],()=>{app.doc.handDrawingReports=app.doc.handDrawingReports||[];app.doc.handDrawingReports.push(report);app.doc.drawingGapRanking=drawingGaps.report();});strokeStatus(`${report.status} · ${report.detection.format} · ${report.inkStrokeSession?.strokes?.length||0} strokes`,report.status==='REJECTED'?'fail':'pass');return report;};
  const importSvgFile=async file=>{if(!file)throw new Error('請選擇 SVG');const svg=await file.text(),paths=importSVGPaths(svg),layer=app.layer();app.history.pushScoped('匯入 SVG',[app.layerObjectsPath(layer)],()=>{layer.objects.push(...paths);app.selection=paths.map(o=>({layerId:layer.id,objectId:o.id}));});app.spatialDirty=true;app.refreshAll();app.fitContent();status(`SVG 已匯入 ${paths.length} 個可編輯 Path`);return{paths,count:paths.length};};
  const importRecipeFile=async file=>{if(!file)throw new Error('請選擇 Recipe');const recipe=JSON.parse(await file.text());engine.registerRecipe(recipe);status(`Recipe ${recipe.id} v${recipe.version} 已載入`);return recipe;};
  const importCalibrationProfileFile=async file=>{if(!file)throw new Error('請選擇 Calibration Profile');const profile=calibrationProfiles.import(await file.text());calibrationProfiles.select(profile.id);stylusRecorder.calibrationProfile=calibrationProfiles.active();status('Calibration Profile 已匯入');return profile;};
  const importReferenceEvidenceFile=async(file,options={})=>{if(!file)throw new Error('請選擇 Reference Evidence');const evidence=JSON.parse(await file.text()),request=referenceRequest(options.runnerId||'manual');if(evidence.assetId!==request.assetId)throw new Error('Reference Evidence Asset ID 不一致');if(evidence.status!=='COMPLETED'||evidence.originalProgramExecuted!==true)throw new Error('Reference Evidence 必須含原軟體實際完成證據');studio.lastReferenceRun=evidence;studio.lastReferencePackage=buildReferencePackage();status('原軟體 Reference Evidence 已匯入，後續差異比較可正式進行');return evidence;};
  const stage=app.el?.canvas;if(stage){stage.addEventListener('pointerdown',event=>{const recorder=studio.activeStrokeRecorder;if(!recorder||recorder.session.status!=='recording'||app.interaction?.type!=='stroke')return;try{recorder.setBrush(activeBrushId(),event.timeStamp);recorder.setColor(app.interaction.object.color,event.timeStamp);recorder.beginStroke({brushId:activeBrushId(),color:app.interaction.object.color,layerId:app.layer().id,seed:(recorder.session.seed+recorder.session.strokes.length)>>>0,timestamp:event.timeStamp});const world=app.renderer.screenToWorld(event.clientX,event.clientY);recorder.addSample({x:world.x,y:world.y,timestamp:event.timeStamp,pressure:event.pressure||.5,tiltX:event.tiltX||0,tiltY:event.tiltY||0,pointerType:event.pointerType});}catch(error){strokeStatus(error.message,'fail');}});stage.addEventListener('pointermove',event=>{const recorder=studio.activeStrokeRecorder;if(!recorder?.active||recorder.session.status!=='recording')return;const events=typeof event.getCoalescedEvents==='function'?event.getCoalescedEvents():[event];for(const item of events){const world=app.renderer.screenToWorld(item.clientX,item.clientY);recorder.addSample({x:world.x,y:world.y,timestamp:item.timeStamp,pressure:item.pressure||.5,tiltX:item.tiltX||0,tiltY:item.tiltY||0,twist:item.twist||0,pointerType:item.pointerType,coalesced:events.length>1});}});const finish=event=>{const recorder=studio.activeStrokeRecorder;if(!recorder?.active)return;try{const world=app.renderer.screenToWorld(event.clientX,event.clientY);recorder.addSample({x:world.x,y:world.y,timestamp:event.timeStamp,pressure:event.pressure||.5,tiltX:event.tiltX||0,tiltY:event.tiltY||0,pointerType:event.pointerType});recorder.endStroke();strokeStatus(`RECORDING · ${recorder.session.strokes.length} strokes`,'pass');}catch(error){strokeStatus(error.message,'fail');}};stage.addEventListener('pointerup',finish);stage.addEventListener('pointercancel',finish);}
  const runStudioQa=()=>{const integrity=globalThis.INK_TEST?.documentIntegrity?.();const qa={version:'1.5.0',fixture:studio.currentFixture?.kind,recipe:engine.replayReport(studio.lastExecutionId),integrity,capabilities:{vectorBoolean:['union','difference','intersection','xor','divide'],image:IMAGE_CAPABILITIES,paint:PAINT_CAPABILITIES,recipe:RECIPE_CAPABILITIES}};status(`QA ${integrity?.passed?'PASS':'FAIL'} · ${qa.recipe?.result?.documentHash||'no recipe'}`,integrity?.passed?'pass':'fail');return qa;};
  globalThis.INK_STUDIO={version:'1.6.0',app,engine,dispatcher,get brushes(){return studio.brushes;},externalAssets,programImporter,referenceRunners,gapRanking,capabilities:{image:IMAGE_CAPABILITIES,paint:PAINT_CAPABILITIES,recipe:RECIPE_CAPABILITIES,programImport:{safetyModes:['STATIC_PARSE','SANDBOX_ANALYSIS','TRANSLATE_ONLY','TRUSTED_EXTERNAL_RUN'],canonicalSchema:1,recipeCompiler:3,referenceComparison:3,referencePackage:1,externalRunner:1},vector:{boolean:['union','difference','intersection','xor','divide'],repeat:['radial','mirror','linear','grid'],editable:true,rasterized:false}},list:()=>dispatcher.list(),schema:id=>dispatcher.schema(id),loadFixture,createFlowerSkeleton,execute,executeStructured:request=>execute({steps:request.steps,fromStep:request.fromStep,toStep:request.toStep,parameters:request.parameters,breakpoints:request.breakpoints,stopAtBreakpoint:request.stopAtBreakpoint}),beginStructured:request=>dispatcher.begin(request),cancel:id=>dispatcher.cancel(id),rollback:id=>dispatcher.rollback(id),report:id=>dispatcher.report(id),boolean:doBoolean,vectorMask:addVectorMask,repeat:addRepeat,expandRepeat:expand,visualDemo,createPaintDemo,importProgram:input=>programImporter.importAsset(input),translateProgram:id=>programImporter.translate(id),programCoverage:(id,evidence)=>programImporter.coverage(id,evidence),gapReport:()=>gapRanking.report(),buildManualReference,buildReferencePackage,importSVG:svg=>importSVGPaths(svg),importSVGFile:importSvgFile,importRecipeFile,importProgramFile,importDrawingFile,importCalibrationProfileFile,importReferenceEvidenceFile,processImageData:(imageData,stack)=>renderImageStack(imageData,stack),layerManifest:()=>createLayerManifest(app.doc),qa:runStudioQa,saveState:()=>clone(app.doc),reloadState:doc=>{app.replaceDocument(clone(doc));app.refreshAll();return true;}};
  Object.assign(globalThis.INK_STUDIO,{version:'1.6.0',drawing:{get brushes(){return studio.brushes;},importBrushPackage:importBrushPackageToDocument,beginSession:beginStrokeRecording,pauseResumeSession:toggleStrokeRecording,finishSession:finishStrokeRecording,replay:(session,options={})=>replayStrokeSession(session,{registry:brushes,...options}),importWorkflow:input=>importDrawingWorkflow(input),gapReport:()=>drawingGaps.report(),stylusRecorder,calibrationProfiles,interactiveBenchmark,PressureCurveEditor,NaturalMediaStateMap},drawingCapabilities:PAINT_CAPABILITIES});
  installAICommandLayer(app);status('Vector／Image／Stroke／Recipe／AI Command 核心已就緒');return globalThis.INK_STUDIO;
}
